name = "umain-platform"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = "dist/server/server.js"

[assets]
directory = "./dist/client"
binding = "STATIC"
not_found_handling = "none"

[[d1_databases]]
binding = "DB"
database_name = "umain-platform"
database_id = "6bb4bfd3-b8dc-413f-9908-011307f3f3e0"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "umain-identity-packs"

pages_build_output_dir = "dist"

# Se agrego la sección de [[r2_buckets]] activación de R2