/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AgencyCatalogRouteImport } from './routes/agency/catalog'
import { Route as ApprovalTokenRouteImport } from './routes/approval/$token'
import { Route as AuditLogIndexRouteImport } from './routes/audit-log/index'
import { Route as CampaignsIndexRouteImport } from './routes/campaigns/index'
import { Route as CastingDashboardRouteImport } from './routes/casting/dashboard'
import { Route as CastingNewTalentRouteImport } from './routes/casting/new-talent'
import { Route as ConsentGateIndexRouteImport } from './routes/consent-gate/index'
import { Route as ContractsIndexRouteImport } from './routes/contracts/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as IdentitiesIndexRouteImport } from './routes/identities/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as LegalIndexRouteImport } from './routes/legal/index'
import { Route as LicensesIndexRouteImport } from './routes/licenses/index'
import { Route as LocksIndexRouteImport } from './routes/locks/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as RoyaltiesIndexRouteImport } from './routes/royalties/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsProvidersRouteImport } from './routes/settings/providers'
import { Route as UsageIndexRouteImport } from './routes/usage/index'
import { Route as AgencyRequestsNewRouteImport } from './routes/agency/requests/new'
import { Route as IdentitiesIdIndexRouteImport } from './routes/identities/$id/index'
import { Route as IdentitiesIdConsentMatrixRouteImport } from './routes/identities/$id/consent-matrix'
import { Route as IdentitiesIdAvatarIndexRouteImport } from './routes/identities/$id/avatar/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyCatalogRoute = AgencyCatalogRouteImport.update({
  id: '/agency/catalog',
  path: '/agency/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalTokenRoute = ApprovalTokenRouteImport.update({
  id: '/approval/$token',
  path: '/approval/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogIndexRoute = AuditLogIndexRouteImport.update({
  id: '/audit-log/',
  path: '/audit-log/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIndexRoute = CampaignsIndexRouteImport.update({
  id: '/campaigns/',
  path: '/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const CastingDashboardRoute = CastingDashboardRouteImport.update({
  id: '/casting/dashboard',
  path: '/casting/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CastingNewTalentRoute = CastingNewTalentRouteImport.update({
  id: '/casting/new-talent',
  path: '/casting/new-talent',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentGateIndexRoute = ConsentGateIndexRouteImport.update({
  id: '/consent-gate/',
  path: '/consent-gate/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentitiesIndexRoute = IdentitiesIndexRouteImport.update({
  id: '/identities/',
  path: '/identities/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesIndexRoute = LicensesIndexRouteImport.update({
  id: '/licenses/',
  path: '/licenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocksIndexRoute = LocksIndexRouteImport.update({
  id: '/locks/',
  path: '/locks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoyaltiesIndexRoute = RoyaltiesIndexRouteImport.update({
  id: '/royalties/',
  path: '/royalties/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/settings/providers',
  path: '/settings/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageIndexRoute = UsageIndexRouteImport.update({
  id: '/usage/',
  path: '/usage/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRequestsNewRoute = AgencyRequestsNewRouteImport.update({
  id: '/agency/requests/new',
  path: '/agency/requests/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentitiesIdIndexRoute = IdentitiesIdIndexRouteImport.update({
  id: '/identities/$id/',
  path: '/identities/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentitiesIdConsentMatrixRoute =
  IdentitiesIdConsentMatrixRouteImport.update({
    id: '/identities/$id/consent-matrix',
    path: '/identities/$id/consent-matrix',
    getParentRoute: () => rootRouteImport,
  } as any)
const IdentitiesIdAvatarIndexRoute = IdentitiesIdAvatarIndexRouteImport.update({
  id: '/identities/$id/avatar/',
  path: '/identities/$id/avatar/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agency/catalog': typeof AgencyCatalogRoute
  '/approval/$token': typeof ApprovalTokenRoute
  '/casting/dashboard': typeof CastingDashboardRoute
  '/casting/new-talent': typeof CastingNewTalentRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/audit-log/': typeof AuditLogIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/consent-gate/': typeof ConsentGateIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/identities/': typeof IdentitiesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/licenses/': typeof LicensesIndexRoute
  '/locks/': typeof LocksIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/royalties/': typeof RoyaltiesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/usage/': typeof UsageIndexRoute
  '/agency/requests/new': typeof AgencyRequestsNewRoute
  '/identities/$id/consent-matrix': typeof IdentitiesIdConsentMatrixRoute
  '/identities/$id/': typeof IdentitiesIdIndexRoute
  '/identities/$id/avatar/': typeof IdentitiesIdAvatarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agency/catalog': typeof AgencyCatalogRoute
  '/approval/$token': typeof ApprovalTokenRoute
  '/casting/dashboard': typeof CastingDashboardRoute
  '/casting/new-talent': typeof CastingNewTalentRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/audit-log': typeof AuditLogIndexRoute
  '/campaigns': typeof CampaignsIndexRoute
  '/consent-gate': typeof ConsentGateIndexRoute
  '/contracts': typeof ContractsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/identities': typeof IdentitiesIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/legal': typeof LegalIndexRoute
  '/licenses': typeof LicensesIndexRoute
  '/locks': typeof LocksIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/royalties': typeof RoyaltiesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/usage': typeof UsageIndexRoute
  '/agency/requests/new': typeof AgencyRequestsNewRoute
  '/identities/$id/consent-matrix': typeof IdentitiesIdConsentMatrixRoute
  '/identities/$id': typeof IdentitiesIdIndexRoute
  '/identities/$id/avatar': typeof IdentitiesIdAvatarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/agency/catalog': typeof AgencyCatalogRoute
  '/approval/$token': typeof ApprovalTokenRoute
  '/casting/dashboard': typeof CastingDashboardRoute
  '/casting/new-talent': typeof CastingNewTalentRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/audit-log/': typeof AuditLogIndexRoute
  '/campaigns/': typeof CampaignsIndexRoute
  '/consent-gate/': typeof ConsentGateIndexRoute
  '/contracts/': typeof ContractsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/identities/': typeof IdentitiesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/licenses/': typeof LicensesIndexRoute
  '/locks/': typeof LocksIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/royalties/': typeof RoyaltiesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/usage/': typeof UsageIndexRoute
  '/agency/requests/new': typeof AgencyRequestsNewRoute
  '/identities/$id/consent-matrix': typeof IdentitiesIdConsentMatrixRoute
  '/identities/$id/': typeof IdentitiesIdIndexRoute
  '/identities/$id/avatar/': typeof IdentitiesIdAvatarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/agency/catalog'
    | '/approval/$token'
    | '/casting/dashboard'
    | '/casting/new-talent'
    | '/settings/providers'
    | '/audit-log/'
    | '/campaigns/'
    | '/consent-gate/'
    | '/contracts/'
    | '/dashboard/'
    | '/docs/'
    | '/identities/'
    | '/jobs/'
    | '/legal/'
    | '/licenses/'
    | '/locks/'
    | '/profile/'
    | '/royalties/'
    | '/settings/'
    | '/usage/'
    | '/agency/requests/new'
    | '/identities/$id/consent-matrix'
    | '/identities/$id/'
    | '/identities/$id/avatar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/agency/catalog'
    | '/approval/$token'
    | '/casting/dashboard'
    | '/casting/new-talent'
    | '/settings/providers'
    | '/audit-log'
    | '/campaigns'
    | '/consent-gate'
    | '/contracts'
    | '/dashboard'
    | '/docs'
    | '/identities'
    | '/jobs'
    | '/legal'
    | '/licenses'
    | '/locks'
    | '/profile'
    | '/royalties'
    | '/settings'
    | '/usage'
    | '/agency/requests/new'
    | '/identities/$id/consent-matrix'
    | '/identities/$id'
    | '/identities/$id/avatar'
  id:
    | '__root__'
    | '/'
    | '/landing'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/agency/catalog'
    | '/approval/$token'
    | '/casting/dashboard'
    | '/casting/new-talent'
    | '/settings/providers'
    | '/audit-log/'
    | '/campaigns/'
    | '/consent-gate/'
    | '/contracts/'
    | '/dashboard/'
    | '/docs/'
    | '/identities/'
    | '/jobs/'
    | '/legal/'
    | '/licenses/'
    | '/locks/'
    | '/profile/'
    | '/royalties/'
    | '/settings/'
    | '/usage/'
    | '/agency/requests/new'
    | '/identities/$id/consent-matrix'
    | '/identities/$id/'
    | '/identities/$id/avatar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AgencyCatalogRoute: typeof AgencyCatalogRoute
  ApprovalTokenRoute: typeof ApprovalTokenRoute
  CastingDashboardRoute: typeof CastingDashboardRoute
  CastingNewTalentRoute: typeof CastingNewTalentRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  AuditLogIndexRoute: typeof AuditLogIndexRoute
  CampaignsIndexRoute: typeof CampaignsIndexRoute
  ConsentGateIndexRoute: typeof ConsentGateIndexRoute
  ContractsIndexRoute: typeof ContractsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  IdentitiesIndexRoute: typeof IdentitiesIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  LegalIndexRoute: typeof LegalIndexRoute
  LicensesIndexRoute: typeof LicensesIndexRoute
  LocksIndexRoute: typeof LocksIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  RoyaltiesIndexRoute: typeof RoyaltiesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  UsageIndexRoute: typeof UsageIndexRoute
  AgencyRequestsNewRoute: typeof AgencyRequestsNewRoute
  IdentitiesIdConsentMatrixRoute: typeof IdentitiesIdConsentMatrixRoute
  IdentitiesIdIndexRoute: typeof IdentitiesIdIndexRoute
  IdentitiesIdAvatarIndexRoute: typeof IdentitiesIdAvatarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/catalog': {
      id: '/agency/catalog'
      path: '/agency/catalog'
      fullPath: '/agency/catalog'
      preLoaderRoute: typeof AgencyCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval/$token': {
      id: '/approval/$token'
      path: '/approval/$token'
      fullPath: '/approval/$token'
      preLoaderRoute: typeof ApprovalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log/': {
      id: '/audit-log/'
      path: '/audit-log'
      fullPath: '/audit-log/'
      preLoaderRoute: typeof AuditLogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/': {
      id: '/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof CampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casting/dashboard': {
      id: '/casting/dashboard'
      path: '/casting/dashboard'
      fullPath: '/casting/dashboard'
      preLoaderRoute: typeof CastingDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casting/new-talent': {
      id: '/casting/new-talent'
      path: '/casting/new-talent'
      fullPath: '/casting/new-talent'
      preLoaderRoute: typeof CastingNewTalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent-gate/': {
      id: '/consent-gate/'
      path: '/consent-gate'
      fullPath: '/consent-gate/'
      preLoaderRoute: typeof ConsentGateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identities/': {
      id: '/identities/'
      path: '/identities'
      fullPath: '/identities/'
      preLoaderRoute: typeof IdentitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses/': {
      id: '/licenses/'
      path: '/licenses'
      fullPath: '/licenses/'
      preLoaderRoute: typeof LicensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locks/': {
      id: '/locks/'
      path: '/locks'
      fullPath: '/locks/'
      preLoaderRoute: typeof LocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/royalties/': {
      id: '/royalties/'
      path: '/royalties'
      fullPath: '/royalties/'
      preLoaderRoute: typeof RoyaltiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/settings/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage/': {
      id: '/usage/'
      path: '/usage'
      fullPath: '/usage/'
      preLoaderRoute: typeof UsageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency/requests/new': {
      id: '/agency/requests/new'
      path: '/agency/requests/new'
      fullPath: '/agency/requests/new'
      preLoaderRoute: typeof AgencyRequestsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identities/$id/': {
      id: '/identities/$id/'
      path: '/identities/$id'
      fullPath: '/identities/$id/'
      preLoaderRoute: typeof IdentitiesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identities/$id/consent-matrix': {
      id: '/identities/$id/consent-matrix'
      path: '/identities/$id/consent-matrix'
      fullPath: '/identities/$id/consent-matrix'
      preLoaderRoute: typeof IdentitiesIdConsentMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identities/$id/avatar/': {
      id: '/identities/$id/avatar/'
      path: '/identities/$id/avatar'
      fullPath: '/identities/$id/avatar/'
      preLoaderRoute: typeof IdentitiesIdAvatarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AgencyCatalogRoute: AgencyCatalogRoute,
  ApprovalTokenRoute: ApprovalTokenRoute,
  CastingDashboardRoute: CastingDashboardRoute,
  CastingNewTalentRoute: CastingNewTalentRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  AuditLogIndexRoute: AuditLogIndexRoute,
  CampaignsIndexRoute: CampaignsIndexRoute,
  ConsentGateIndexRoute: ConsentGateIndexRoute,
  ContractsIndexRoute: ContractsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  IdentitiesIndexRoute: IdentitiesIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  LegalIndexRoute: LegalIndexRoute,
  LicensesIndexRoute: LicensesIndexRoute,
  LocksIndexRoute: LocksIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  RoyaltiesIndexRoute: RoyaltiesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  UsageIndexRoute: UsageIndexRoute,
  AgencyRequestsNewRoute: AgencyRequestsNewRoute,
  IdentitiesIdConsentMatrixRoute: IdentitiesIdConsentMatrixRoute,
  IdentitiesIdIndexRoute: IdentitiesIdIndexRoute,
  IdentitiesIdAvatarIndexRoute: IdentitiesIdAvatarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
